/* nonpolymer */
BEGIN TRANSACTION;
DROP TABLE IF EXISTS Refaco_tmp;
CREATE TABLE Refaco_tmp AS SELECT * FROM Refaco_nonpolymer;
DELETE FROM Refaco_nonpolymer ;
ALTER TABLE Refaco_nonpolymer0 DROP CONSTRAINT refaco_nonpolymer0_pdbcode_check;
ALTER TABLE Refaco_nonpolymer0 ADD CONSTRAINT refaco_nonpolymer0_pdbcode_check CHECK (((pdbcode / 23) % 10) = 0);
DROP INDEX refaco_nonpolymer0_geom;
ALTER TABLE Refaco_nonpolymer1 DROP CONSTRAINT refaco_nonpolymer1_pdbcode_check;
ALTER TABLE Refaco_nonpolymer1 ADD CONSTRAINT refaco_nonpolymer1_pdbcode_check CHECK (((pdbcode / 23) % 10) = 1);
DROP INDEX refaco_nonpolymer1_geom;
ALTER TABLE Refaco_nonpolymer2 DROP CONSTRAINT refaco_nonpolymer2_pdbcode_check;
ALTER TABLE Refaco_nonpolymer2 ADD CONSTRAINT refaco_nonpolymer2_pdbcode_check CHECK (((pdbcode / 23) % 10) = 2);
DROP INDEX refaco_nonpolymer2_geom;
ALTER TABLE Refaco_nonpolymer3 DROP CONSTRAINT refaco_nonpolymer3_pdbcode_check;
ALTER TABLE Refaco_nonpolymer3 ADD CONSTRAINT refaco_nonpolymer3_pdbcode_check CHECK (((pdbcode / 23) % 10) = 3);
DROP INDEX refaco_nonpolymer3_geom;
ALTER TABLE Refaco_nonpolymer4 DROP CONSTRAINT refaco_nonpolymer4_pdbcode_check;
ALTER TABLE Refaco_nonpolymer4 ADD CONSTRAINT refaco_nonpolymer4_pdbcode_check CHECK (((pdbcode / 23) % 10) = 4);
DROP INDEX refaco_nonpolymer4_geom;
ALTER TABLE Refaco_nonpolymer5 DROP CONSTRAINT refaco_nonpolymer5_pdbcode_check;
ALTER TABLE Refaco_nonpolymer5 ADD CONSTRAINT refaco_nonpolymer5_pdbcode_check CHECK (((pdbcode / 23) % 10) = 5);
DROP INDEX refaco_nonpolymer5_geom;
ALTER TABLE Refaco_nonpolymer6 DROP CONSTRAINT refaco_nonpolymer6_pdbcode_check;
ALTER TABLE Refaco_nonpolymer6 ADD CONSTRAINT refaco_nonpolymer6_pdbcode_check CHECK (((pdbcode / 23) % 10) = 6);
DROP INDEX refaco_nonpolymer6_geom;
ALTER TABLE Refaco_nonpolymer7 DROP CONSTRAINT refaco_nonpolymer7_pdbcode_check;
ALTER TABLE Refaco_nonpolymer7 ADD CONSTRAINT refaco_nonpolymer7_pdbcode_check CHECK (((pdbcode / 23) % 10) = 7);
DROP INDEX refaco_nonpolymer7_geom;
ALTER TABLE Refaco_nonpolymer8 DROP CONSTRAINT refaco_nonpolymer8_pdbcode_check;
ALTER TABLE Refaco_nonpolymer8 ADD CONSTRAINT refaco_nonpolymer8_pdbcode_check CHECK (((pdbcode / 23) % 10) = 8);
DROP INDEX refaco_nonpolymer8_geom;
ALTER TABLE Refaco_nonpolymer9 DROP CONSTRAINT refaco_nonpolymer9_pdbcode_check;
ALTER TABLE Refaco_nonpolymer9 ADD CONSTRAINT refaco_nonpolymer9_pdbcode_check CHECK (((pdbcode / 23) % 10) = 9);
DROP INDEX refaco_nonpolymer9_geom;
INSERT INTO Refaco_nonpolymer SELECT * FROM Refaco_tmp;
DROP TABLE Refaco_tmp;
COMMIT; 
/* dnarna */
BEGIN TRANSACTION;
DROP TABLE IF EXISTS Refaco_tmp;
CREATE TABLE Refaco_tmp AS SELECT * FROM Refaco_dnarna;
DELETE FROM Refaco_dnarna ;
ALTER TABLE Refaco_dnarna0 DROP CONSTRAINT refaco_dnarna0_pdbcode_check;
ALTER TABLE Refaco_dnarna0 ADD CONSTRAINT refaco_dnarna0_pdbcode_check CHECK (((pdbcode / 23) % 10) = 0);
DROP INDEX refaco_dnarna0_geom;
ALTER TABLE Refaco_dnarna1 DROP CONSTRAINT refaco_dnarna1_pdbcode_check;
ALTER TABLE Refaco_dnarna1 ADD CONSTRAINT refaco_dnarna1_pdbcode_check CHECK (((pdbcode / 23) % 10) = 1);
DROP INDEX refaco_dnarna1_geom;
ALTER TABLE Refaco_dnarna2 DROP CONSTRAINT refaco_dnarna2_pdbcode_check;
ALTER TABLE Refaco_dnarna2 ADD CONSTRAINT refaco_dnarna2_pdbcode_check CHECK (((pdbcode / 23) % 10) = 2);
DROP INDEX refaco_dnarna2_geom;
ALTER TABLE Refaco_dnarna3 DROP CONSTRAINT refaco_dnarna3_pdbcode_check;
ALTER TABLE Refaco_dnarna3 ADD CONSTRAINT refaco_dnarna3_pdbcode_check CHECK (((pdbcode / 23) % 10) = 3);
DROP INDEX refaco_dnarna3_geom;
ALTER TABLE Refaco_dnarna4 DROP CONSTRAINT refaco_dnarna4_pdbcode_check;
ALTER TABLE Refaco_dnarna4 ADD CONSTRAINT refaco_dnarna4_pdbcode_check CHECK (((pdbcode / 23) % 10) = 4);
DROP INDEX refaco_dnarna4_geom;
ALTER TABLE Refaco_dnarna5 DROP CONSTRAINT refaco_dnarna5_pdbcode_check;
ALTER TABLE Refaco_dnarna5 ADD CONSTRAINT refaco_dnarna5_pdbcode_check CHECK (((pdbcode / 23) % 10) = 5);
DROP INDEX refaco_dnarna5_geom;
ALTER TABLE Refaco_dnarna6 DROP CONSTRAINT refaco_dnarna6_pdbcode_check;
ALTER TABLE Refaco_dnarna6 ADD CONSTRAINT refaco_dnarna6_pdbcode_check CHECK (((pdbcode / 23) % 10) = 6);
DROP INDEX refaco_dnarna6_geom;
ALTER TABLE Refaco_dnarna7 DROP CONSTRAINT refaco_dnarna7_pdbcode_check;
ALTER TABLE Refaco_dnarna7 ADD CONSTRAINT refaco_dnarna7_pdbcode_check CHECK (((pdbcode / 23) % 10) = 7);
DROP INDEX refaco_dnarna7_geom;
ALTER TABLE Refaco_dnarna8 DROP CONSTRAINT refaco_dnarna8_pdbcode_check;
ALTER TABLE Refaco_dnarna8 ADD CONSTRAINT refaco_dnarna8_pdbcode_check CHECK (((pdbcode / 23) % 10) = 8);
DROP INDEX refaco_dnarna8_geom;
ALTER TABLE Refaco_dnarna9 DROP CONSTRAINT refaco_dnarna9_pdbcode_check;
ALTER TABLE Refaco_dnarna9 ADD CONSTRAINT refaco_dnarna9_pdbcode_check CHECK (((pdbcode / 23) % 10) = 9);
DROP INDEX refaco_dnarna9_geom;
INSERT INTO Refaco_dnarna SELECT * FROM Refaco_tmp;
DROP TABLE Refaco_tmp;
COMMIT; 
/* ppi */
BEGIN TRANSACTION;
DROP TABLE IF EXISTS Refaco_tmp;
CREATE TABLE Refaco_tmp AS SELECT * FROM Refaco_ppi;
DELETE FROM Refaco_ppi ;
ALTER TABLE Refaco_ppi0 DROP CONSTRAINT refaco_ppi0_pdbcode_check;
ALTER TABLE Refaco_ppi0 ADD CONSTRAINT refaco_ppi0_pdbcode_check CHECK (((pdbcode / 23) % 10) = 0);
DROP INDEX refaco_ppi0_geom;
ALTER TABLE Refaco_ppi1 DROP CONSTRAINT refaco_ppi1_pdbcode_check;
ALTER TABLE Refaco_ppi1 ADD CONSTRAINT refaco_ppi1_pdbcode_check CHECK (((pdbcode / 23) % 10) = 1);
DROP INDEX refaco_ppi1_geom;
ALTER TABLE Refaco_ppi2 DROP CONSTRAINT refaco_ppi2_pdbcode_check;
ALTER TABLE Refaco_ppi2 ADD CONSTRAINT refaco_ppi2_pdbcode_check CHECK (((pdbcode / 23) % 10) = 2);
DROP INDEX refaco_ppi2_geom;
ALTER TABLE Refaco_ppi3 DROP CONSTRAINT refaco_ppi3_pdbcode_check;
ALTER TABLE Refaco_ppi3 ADD CONSTRAINT refaco_ppi3_pdbcode_check CHECK (((pdbcode / 23) % 10) = 3);
DROP INDEX refaco_ppi3_geom;
ALTER TABLE Refaco_ppi4 DROP CONSTRAINT refaco_ppi4_pdbcode_check;
ALTER TABLE Refaco_ppi4 ADD CONSTRAINT refaco_ppi4_pdbcode_check CHECK (((pdbcode / 23) % 10) = 4);
DROP INDEX refaco_ppi4_geom;
ALTER TABLE Refaco_ppi5 DROP CONSTRAINT refaco_ppi5_pdbcode_check;
ALTER TABLE Refaco_ppi5 ADD CONSTRAINT refaco_ppi5_pdbcode_check CHECK (((pdbcode / 23) % 10) = 5);
DROP INDEX refaco_ppi5_geom;
ALTER TABLE Refaco_ppi6 DROP CONSTRAINT refaco_ppi6_pdbcode_check;
ALTER TABLE Refaco_ppi6 ADD CONSTRAINT refaco_ppi6_pdbcode_check CHECK (((pdbcode / 23) % 10) = 6);
DROP INDEX refaco_ppi6_geom;
ALTER TABLE Refaco_ppi7 DROP CONSTRAINT refaco_ppi7_pdbcode_check;
ALTER TABLE Refaco_ppi7 ADD CONSTRAINT refaco_ppi7_pdbcode_check CHECK (((pdbcode / 23) % 10) = 7);
DROP INDEX refaco_ppi7_geom;
ALTER TABLE Refaco_ppi8 DROP CONSTRAINT refaco_ppi8_pdbcode_check;
ALTER TABLE Refaco_ppi8 ADD CONSTRAINT refaco_ppi8_pdbcode_check CHECK (((pdbcode / 23) % 10) = 8);
DROP INDEX refaco_ppi8_geom;
ALTER TABLE Refaco_ppi9 DROP CONSTRAINT refaco_ppi9_pdbcode_check;
ALTER TABLE Refaco_ppi9 ADD CONSTRAINT refaco_ppi9_pdbcode_check CHECK (((pdbcode / 23) % 10) = 9);
DROP INDEX refaco_ppi9_geom;
INSERT INTO Refaco_ppi SELECT * FROM Refaco_tmp;
DROP TABLE Refaco_tmp;
COMMIT; 
/* peptide */
BEGIN TRANSACTION;
DROP TABLE IF EXISTS Refaco_tmp;
CREATE TABLE Refaco_tmp AS SELECT * FROM Refaco_peptide;
DELETE FROM Refaco_peptide ;
ALTER TABLE Refaco_peptide0 DROP CONSTRAINT refaco_peptide0_pdbcode_check;
ALTER TABLE Refaco_peptide0 ADD CONSTRAINT refaco_peptide0_pdbcode_check CHECK (((pdbcode / 23) % 10) = 0);
DROP INDEX refaco_peptide0_geom;
ALTER TABLE Refaco_peptide1 DROP CONSTRAINT refaco_peptide1_pdbcode_check;
ALTER TABLE Refaco_peptide1 ADD CONSTRAINT refaco_peptide1_pdbcode_check CHECK (((pdbcode / 23) % 10) = 1);
DROP INDEX refaco_peptide1_geom;
ALTER TABLE Refaco_peptide2 DROP CONSTRAINT refaco_peptide2_pdbcode_check;
ALTER TABLE Refaco_peptide2 ADD CONSTRAINT refaco_peptide2_pdbcode_check CHECK (((pdbcode / 23) % 10) = 2);
DROP INDEX refaco_peptide2_geom;
ALTER TABLE Refaco_peptide3 DROP CONSTRAINT refaco_peptide3_pdbcode_check;
ALTER TABLE Refaco_peptide3 ADD CONSTRAINT refaco_peptide3_pdbcode_check CHECK (((pdbcode / 23) % 10) = 3);
DROP INDEX refaco_peptide3_geom;
ALTER TABLE Refaco_peptide4 DROP CONSTRAINT refaco_peptide4_pdbcode_check;
ALTER TABLE Refaco_peptide4 ADD CONSTRAINT refaco_peptide4_pdbcode_check CHECK (((pdbcode / 23) % 10) = 4);
DROP INDEX refaco_peptide4_geom;
ALTER TABLE Refaco_peptide5 DROP CONSTRAINT refaco_peptide5_pdbcode_check;
ALTER TABLE Refaco_peptide5 ADD CONSTRAINT refaco_peptide5_pdbcode_check CHECK (((pdbcode / 23) % 10) = 5);
DROP INDEX refaco_peptide5_geom;
ALTER TABLE Refaco_peptide6 DROP CONSTRAINT refaco_peptide6_pdbcode_check;
ALTER TABLE Refaco_peptide6 ADD CONSTRAINT refaco_peptide6_pdbcode_check CHECK (((pdbcode / 23) % 10) = 6);
DROP INDEX refaco_peptide6_geom;
ALTER TABLE Refaco_peptide7 DROP CONSTRAINT refaco_peptide7_pdbcode_check;
ALTER TABLE Refaco_peptide7 ADD CONSTRAINT refaco_peptide7_pdbcode_check CHECK (((pdbcode / 23) % 10) = 7);
DROP INDEX refaco_peptide7_geom;
ALTER TABLE Refaco_peptide8 DROP CONSTRAINT refaco_peptide8_pdbcode_check;
ALTER TABLE Refaco_peptide8 ADD CONSTRAINT refaco_peptide8_pdbcode_check CHECK (((pdbcode / 23) % 10) = 8);
DROP INDEX refaco_peptide8_geom;
ALTER TABLE Refaco_peptide9 DROP CONSTRAINT refaco_peptide9_pdbcode_check;
ALTER TABLE Refaco_peptide9 ADD CONSTRAINT refaco_peptide9_pdbcode_check CHECK (((pdbcode / 23) % 10) = 9);
DROP INDEX refaco_peptide9_geom;
INSERT INTO Refaco_peptide SELECT * FROM Refaco_tmp;
DROP TABLE Refaco_tmp;
COMMIT; 
/* opoly */
BEGIN TRANSACTION;
DROP TABLE IF EXISTS Refaco_tmp;
CREATE TABLE Refaco_tmp AS SELECT * FROM Refaco_opoly;
DELETE FROM Refaco_opoly ;
ALTER TABLE Refaco_opoly0 DROP CONSTRAINT refaco_opoly0_pdbcode_check;
ALTER TABLE Refaco_opoly0 ADD CONSTRAINT refaco_opoly0_pdbcode_check CHECK (((pdbcode / 23) % 10) = 0);
DROP INDEX refaco_opoly0_geom;
ALTER TABLE Refaco_opoly1 DROP CONSTRAINT refaco_opoly1_pdbcode_check;
ALTER TABLE Refaco_opoly1 ADD CONSTRAINT refaco_opoly1_pdbcode_check CHECK (((pdbcode / 23) % 10) = 1);
DROP INDEX refaco_opoly1_geom;
ALTER TABLE Refaco_opoly2 DROP CONSTRAINT refaco_opoly2_pdbcode_check;
ALTER TABLE Refaco_opoly2 ADD CONSTRAINT refaco_opoly2_pdbcode_check CHECK (((pdbcode / 23) % 10) = 2);
DROP INDEX refaco_opoly2_geom;
ALTER TABLE Refaco_opoly3 DROP CONSTRAINT refaco_opoly3_pdbcode_check;
ALTER TABLE Refaco_opoly3 ADD CONSTRAINT refaco_opoly3_pdbcode_check CHECK (((pdbcode / 23) % 10) = 3);
DROP INDEX refaco_opoly3_geom;
ALTER TABLE Refaco_opoly4 DROP CONSTRAINT refaco_opoly4_pdbcode_check;
ALTER TABLE Refaco_opoly4 ADD CONSTRAINT refaco_opoly4_pdbcode_check CHECK (((pdbcode / 23) % 10) = 4);
DROP INDEX refaco_opoly4_geom;
ALTER TABLE Refaco_opoly5 DROP CONSTRAINT refaco_opoly5_pdbcode_check;
ALTER TABLE Refaco_opoly5 ADD CONSTRAINT refaco_opoly5_pdbcode_check CHECK (((pdbcode / 23) % 10) = 5);
DROP INDEX refaco_opoly5_geom;
ALTER TABLE Refaco_opoly6 DROP CONSTRAINT refaco_opoly6_pdbcode_check;
ALTER TABLE Refaco_opoly6 ADD CONSTRAINT refaco_opoly6_pdbcode_check CHECK (((pdbcode / 23) % 10) = 6);
DROP INDEX refaco_opoly6_geom;
ALTER TABLE Refaco_opoly7 DROP CONSTRAINT refaco_opoly7_pdbcode_check;
ALTER TABLE Refaco_opoly7 ADD CONSTRAINT refaco_opoly7_pdbcode_check CHECK (((pdbcode / 23) % 10) = 7);
DROP INDEX refaco_opoly7_geom;
ALTER TABLE Refaco_opoly8 DROP CONSTRAINT refaco_opoly8_pdbcode_check;
ALTER TABLE Refaco_opoly8 ADD CONSTRAINT refaco_opoly8_pdbcode_check CHECK (((pdbcode / 23) % 10) = 8);
DROP INDEX refaco_opoly8_geom;
ALTER TABLE Refaco_opoly9 DROP CONSTRAINT refaco_opoly9_pdbcode_check;
ALTER TABLE Refaco_opoly9 ADD CONSTRAINT refaco_opoly9_pdbcode_check CHECK (((pdbcode / 23) % 10) = 9);
DROP INDEX refaco_opoly9_geom;
INSERT INTO Refaco_opoly SELECT * FROM Refaco_tmp;
DROP TABLE Refaco_tmp;
COMMIT; 
